### ISSUE TITLE
estimate cnn feat std

### ISSUE THREAD

**Issue by fatemehkalantari1993** [KamitaniLab/brain-decoding-cookbook-public#6]
Hi, 
How did you provide this file??

estimated_cnn_feat_std_VGG_ILSVRC_19_layers_ImgSize_224x224_chwise_dof1.mat

**Comment by fatemehkalantari1993** [comment]
​I think I should use estimate_cnn_feat_std in utils.py for true images. in your code, you said that you used 10000 images for this task. what are these???

**Comment by ShuntaroAoki** [comment]
The file is included in VGG-19 model files. You can donwload them with the download script (https://github.com/KamitaniLab/brain-decoding-cookbook-public/blob/main/reconstruction/models/download.sh).

**Comment by fatemehkalantari1993** [comment]
​I know, But I want to make this file for another network.

**Comment by ShuntaroAoki** [comment]
Ah, I see.
I've uploaded the 10,000 images. Now you can find them at <https://drive.google.com/file/d/1cJ-7zXs4rPS0ssJ3-F1X69REtSVN6Al5/view?usp=drive_link>.

**Comment by fatemehkalantari1993** [comment]
​Hi Thank you for your helpfirst, I extract features of 10000 images as 10000 .mat files in each layer and then I calculate the std of 10000 .mat files in each layer and finally, I calculate the mean of them in each layer. is this method true???
I just want to be sure this method is correct or not.
